### ISSUE TITLE
Allow File Name Overrides on Direct Access URL Requests

### ISSUE THREAD

**Issue by canpan14** [Alfresco/alfresco-community-repo#2064]
When retrieving a content URL for nodes, renditions, or versions, a file name body parameter should be allowed so files can be downloaded with a user supplied name.

This would allow easier integration with external metadata databases, setups where the source of the file name isn't consistent, or situations where the file name is often changed, requiring frequent API calls.

I plan on throwing together some code for this and linking to this issue, but most of the repo's supporting links are dead so let me know if I should proceed differently.

**Comment by tpage-alfresco** [comment]
Thanks for the contribution! We'll try to review it and get back to you.

Some of the links seem to be dead because our community hub moved location. I'll try to update those shortly. Having looked through the code then it all seems to be in line with our standards. :+1:

**Comment by canpan14** [comment]
@tpage-alfresco Awesome! I added some unit tests and ignore the override in case of an empty string.

**Comment by tpage-alfresco** [comment]
Thank you for the contribution!
